auth_key: ~/.ssh/id_rsa

machines:

  - name: bridges2
    host: bridges2.psc.edu
    user: user

  - name: expanse
    host: expanse.sdsc.edu
    user: user

  - name: anvil
    host: anvil.rcac.purdue.edu
    user: user

commands:
  squeue: squeue -u $(whoami) -o %all
